# docker-compose.yml
version: "3.9"
services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - APM_SERVICE_NAME=flask-app
      - APM_SECRET_TOKEN=SQFLIUswj2Nycm3Ble
      - APM_SERVER_URL=https://8df3574129ac416ab567aab0bdeeea69.apm.us-west2.gcp.elastic-cloud.com:443
